import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';
import { logger } from '@/utils/logger';

const prisma = new PrismaClient();

// Dados das 18 províncias de Angola
const provincesData = [
  {
    name: 'Luanda',
    code: 'LDA',
    capital: 'Luanda',
    population: '8.3 milhões',
    area: '18.826 km²',
    density: '441 hab/km²',
    region: 'Norte',
    timezone: 'WAT (UTC+1)',
    currency: 'Kwanza (AOA)',
    language: 'Português',
    religion: 'Cristianismo',
    government: 'Provincial',
    chiefAdministrator: 'Governador',
    areaCode: '222',
    postalCode: '1000-9999',
    latitude: -8.8390,
    longitude: 13.2894,
  },
  {
    name: 'Huíla',
    code: 'HUI',
    capital: 'Lubango',
    population: '2.8 milhões',
    area: '79.023 km²',
    density: '35 hab/km²',
    region: 'Sul',
    timezone: 'WAT (UTC+1)',
    currency: 'Kwanza (AOA)',
    language: 'Português',
    religion: 'Cristianismo',
    government: 'Provincial',
    chiefAdministrator: 'Governador',
    areaCode: '261',
    postalCode: '2000-2999',
    latitude: -14.9177,
    longitude: 13.4925,
  },
  {
    name: 'Benguela',
    code: 'BEN',
    capital: 'Benguela',
    population: '2.2 milhões',
    area: '31.788 km²',
    density: '69 hab/km²',
    region: 'Centro',
    timezone: 'WAT (UTC+1)',
    currency: 'Kwanza (AOA)',
    language: 'Português',
    religion: 'Cristianismo',
    government: 'Provincial',
    chiefAdministrator: 'Governador',
    areaCode: '244',
    postalCode: '3000-3999',
    latitude: -12.5763,
    longitude: 13.4055,
  },
  {
    name: 'Huambo',
    code: 'HUA',
    capital: 'Huambo',
    population: '2.0 milhões',
    area: '34.274 km²',
    density: '58 hab/km²',
    region: 'Centro',
    timezone: 'WAT (UTC+1)',
    currency: 'Kwanza (AOA)',
    language: 'Português',
    religion: 'Cristianismo',
    government: 'Provincial',
    chiefAdministrator: 'Governador',
    areaCode: '241',
    postalCode: '4000-4999',
    latitude: -12.7761,
    longitude: 15.7390,
  },
  {
    name: 'Cabinda',
    code: 'CAB',
    capital: 'Cabinda',
    population: '716 mil',
    area: '7.283 km²',
    density: '98 hab/km²',
    region: 'Norte',
    timezone: 'WAT (UTC+1)',
    currency: 'Kwanza (AOA)',
    language: 'Português',
    religion: 'Cristianismo',
    government: 'Provincial',
    chiefAdministrator: 'Governador',
    areaCode: '231',
    postalCode: '5000-5999',
    latitude: -5.5506,
    longitude: 12.1972,
  },
  {
    name: 'Zaire',
    code: 'ZAI',
    capital: 'Mbanza Kongo',
    population: '594 mil',
    area: '40.130 km²',
    density: '15 hab/km²',
    region: 'Norte',
    timezone: 'WAT (UTC+1)',
    currency: 'Kwanza (AOA)',
    language: 'Português',
    religion: 'Cristianismo',
    government: 'Provincial',
    chiefAdministrator: 'Governador',
    areaCode: '232',
    postalCode: '6000-6999',
    latitude: -6.2670,
    longitude: 14.2401,
  },
  {
    name: 'Uíge',
    code: 'UIG',
    capital: 'Uíge',
    population: '1.5 milhões',
    area: '58.698 km²',
    density: '26 hab/km²',
    region: 'Norte',
    timezone: 'WAT (UTC+1)',
    currency: 'Kwanza (AOA)',
    language: 'Português',
    religion: 'Cristianismo',
    government: 'Provincial',
    chiefAdministrator: 'Governador',
    areaCode: '233',
    postalCode: '7000-7999',
    latitude: -7.6089,
    longitude: 15.0613,
  },
  {
    name: 'Cuanza Norte',
    code: 'CNO',
    capital: 'Ndalatando',
    population: '443 mil',
    area: '24.110 km²',
    density: '18 hab/km²',
    region: 'Norte',
    timezone: 'WAT (UTC+1)',
    currency: 'Kwanza (AOA)',
    language: 'Português',
    religion: 'Cristianismo',
    government: 'Provincial',
    chiefAdministrator: 'Governador',
    areaCode: '234',
    postalCode: '8000-8999',
    latitude: -9.2978,
    longitude: 14.9116,
  },
  {
    name: 'Cuanza Sul',
    code: 'CSU',
    capital: 'Sumbe',
    population: '1.9 milhões',
    area: '55.660 km²',
    density: '34 hab/km²',
    region: 'Centro',
    timezone: 'WAT (UTC+1)',
    currency: 'Kwanza (AOA)',
    language: 'Português',
    religion: 'Cristianismo',
    government: 'Provincial',
    chiefAdministrator: 'Governador',
    areaCode: '235',
    postalCode: '9000-9999',
    latitude: -11.2027,
    longitude: 13.8417,
  },
  {
    name: 'Malanje',
    code: 'MAL',
    capital: 'Malanje',
    population: '986 mil',
    area: '98.302 km²',
    density: '10 hab/km²',
    region: 'Norte',
    timezone: 'WAT (UTC+1)',
    currency: 'Kwanza (AOA)',
    language: 'Português',
    religion: 'Cristianismo',
    government: 'Provincial',
    chiefAdministrator: 'Governador',
    areaCode: '236',
    postalCode: '10000-10999',
    latitude: -9.5407,
    longitude: 16.3346,
  },
  {
    name: 'Lunda Norte',
    code: 'LNO',
    capital: 'Dundo',
    population: '862 mil',
    area: '102.783 km²',
    density: '8 hab/km²',
    region: 'Norte',
    timezone: 'WAT (UTC+1)',
    currency: 'Kwanza (AOA)',
    language: 'Português',
    religion: 'Cristianismo',
    government: 'Provincial',
    chiefAdministrator: 'Governador',
    areaCode: '237',
    postalCode: '11000-11999',
    latitude: -7.4167,
    longitude: 20.8333,
  },
  {
    name: 'Lunda Sul',
    code: 'LSU',
    capital: 'Saurimo',
    population: '537 mil',
    area: '77.637 km²',
    density: '7 hab/km²',
    region: 'Norte',
    timezone: 'WAT (UTC+1)',
    currency: 'Kwanza (AOA)',
    language: 'Português',
    religion: 'Cristianismo',
    government: 'Provincial',
    chiefAdministrator: 'Governador',
    areaCode: '238',
    postalCode: '12000-12999',
    latitude: -9.6589,
    longitude: 20.3939,
  },
  {
    name: 'Moxico',
    code: 'MOX',
    capital: 'Luena',
    population: '758 mil',
    area: '223.023 km²',
    density: '3 hab/km²',
    region: 'Centro',
    timezone: 'WAT (UTC+1)',
    currency: 'Kwanza (AOA)',
    language: 'Português',
    religion: 'Cristianismo',
    government: 'Provincial',
    chiefAdministrator: 'Governador',
    areaCode: '239',
    postalCode: '13000-13999',
    latitude: -11.7881,
    longitude: 19.9062,
  },
  {
    name: 'Bié',
    code: 'BIE',
    capital: 'Kuito',
    population: '1.4 milhões',
    area: '70.314 km²',
    density: '20 hab/km²',
    region: 'Centro',
    timezone: 'WAT (UTC+1)',
    currency: 'Kwanza (AOA)',
    language: 'Português',
    religion: 'Cristianismo',
    government: 'Provincial',
    chiefAdministrator: 'Governador',
    areaCode: '240',
    postalCode: '14000-14999',
    latitude: -12.1900,
    longitude: 16.9400,
  },
  {
    name: 'Cuando Cubango',
    code: 'CCU',
    capital: 'Menongue',
    population: '534 mil',
    area: '199.049 km²',
    density: '3 hab/km²',
    region: 'Sul',
    timezone: 'WAT (UTC+1)',
    currency: 'Kwanza (AOA)',
    language: 'Português',
    religion: 'Cristianismo',
    government: 'Provincial',
    chiefAdministrator: 'Governador',
    areaCode: '262',
    postalCode: '15000-15999',
    latitude: -14.6581,
    longitude: 17.6906,
  },
  {
    name: 'Namibe',
    code: 'NAM',
    capital: 'Namibe',
    population: '495 mil',
    area: '57.091 km²',
    density: '9 hab/km²',
    region: 'Sul',
    timezone: 'WAT (UTC+1)',
    currency: 'Kwanza (AOA)',
    language: 'Português',
    religion: 'Cristianismo',
    government: 'Provincial',
    chiefAdministrator: 'Governador',
    areaCode: '263',
    postalCode: '16000-16999',
    latitude: -15.1961,
    longitude: 12.1522,
  },
  {
    name: 'Cunene',
    code: 'CUN',
    capital: 'Ondjiva',
    population: '990 mil',
    area: '87.342 km²',
    density: '11 hab/km²',
    region: 'Sul',
    timezone: 'WAT (UTC+1)',
    currency: 'Kwanza (AOA)',
    language: 'Português',
    religion: 'Cristianismo',
    government: 'Provincial',
    chiefAdministrator: 'Governador',
    areaCode: '264',
    postalCode: '17000-17999',
    latitude: -16.8333,
    longitude: 15.7500,
  },
];

// Dados de alguns municípios principais (exemplo)
const municipalitiesData = [
  // Luanda
  {
    name: 'Luanda',
    code: 'LDA001',
    provinceCode: 'LDA',
    population: '2.8 milhões',
    area: '2.257 km²',
    density: '1.241 hab/km²',
    region: 'Norte',
    timezone: 'WAT (UTC+1)',
    currency: 'Kwanza (AOA)',
    language: 'Português',
    religion: 'Cristianismo',
    government: 'Municipal',
    chiefAdministrator: 'Administrador',
    areaCode: '222',
    postalCode: '1000-1999',
    latitude: -8.8390,
    longitude: 13.2894,
  },
  {
    name: 'Cazenga',
    code: 'LDA002',
    provinceCode: 'LDA',
    population: '1.2 milhões',
    area: '37 km²',
    density: '32.432 hab/km²',
    region: 'Norte',
    timezone: 'WAT (UTC+1)',
    currency: 'Kwanza (AOA)',
    language: 'Português',
    religion: 'Cristianismo',
    government: 'Municipal',
    chiefAdministrator: 'Administrador',
    areaCode: '222',
    postalCode: '2000-2999',
    latitude: -8.8500,
    longitude: 13.3000,
  },
  {
    name: 'Viana',
    code: 'LDA003',
    provinceCode: 'LDA',
    population: '1.0 milhão',
    area: '1.000 km²',
    density: '1.000 hab/km²',
    region: 'Norte',
    timezone: 'WAT (UTC+1)',
    currency: 'Kwanza (AOA)',
    language: 'Português',
    religion: 'Cristianismo',
    government: 'Municipal',
    chiefAdministrator: 'Administrador',
    areaCode: '222',
    postalCode: '3000-3999',
    latitude: -8.9000,
    longitude: 13.2500,
  },
  // Huíla
  {
    name: 'Lubango',
    code: 'HUI001',
    provinceCode: 'HUI',
    population: '1.0 milhão',
    area: '3.140 km²',
    density: '319 hab/km²',
    region: 'Sul',
    timezone: 'WAT (UTC+1)',
    currency: 'Kwanza (AOA)',
    language: 'Português',
    religion: 'Cristianismo',
    government: 'Municipal',
    chiefAdministrator: 'Administrador',
    areaCode: '261',
    postalCode: '2000-2999',
    latitude: -14.9177,
    longitude: 13.4925,
  },
  // Benguela
  {
    name: 'Benguela',
    code: 'BEN001',
    provinceCode: 'BEN',
    population: '600 mil',
    area: '2.100 km²',
    density: '286 hab/km²',
    region: 'Centro',
    timezone: 'WAT (UTC+1)',
    currency: 'Kwanza (AOA)',
    language: 'Português',
    religion: 'Cristianismo',
    government: 'Municipal',
    chiefAdministrator: 'Administrador',
    areaCode: '244',
    postalCode: '3000-3999',
    latitude: -12.5763,
    longitude: 13.4055,
  },
];

async function main() {
  try {
    logger.info('🌱 Iniciando seed do banco de dados...');

    // Clear existing data
    await prisma.municipality.deleteMany();
    await prisma.province.deleteMany();
    await prisma.user.deleteMany();

    logger.info('🗑️ Dados existentes removidos');

    // Create provinces
    logger.info('🏛️ Criando províncias...');
    for (const provinceData of provincesData) {
      await prisma.province.create({
        data: provinceData,
      });
    }
    logger.info(`✅ ${provincesData.length} províncias criadas`);

    // Create municipalities
    logger.info('🏘️ Criando municípios...');
    for (const municipalityData of municipalitiesData) {
      await prisma.municipality.create({
        data: municipalityData,
      });
    }
    logger.info(`✅ ${municipalitiesData.length} municípios criados`);

    // Create admin user
    logger.info('👤 Criando usuário administrador...');
    const hashedPassword = await bcrypt.hash('admin123', 12);
    await prisma.user.create({
      data: {
        name: 'Administrador',
        email: 'admin@angola-localization.com',
        password: hashedPassword,
        role: 'ADMIN',
        isActive: true,
      },
    });
    logger.info('✅ Usuário administrador criado (admin@angola-localization.com / admin123)');

    // Create owner user
    logger.info('👑 Criando usuário proprietário...');
    await prisma.user.create({
      data: {
        name: 'Proprietário',
        email: 'owner@angola-localization.com',
        password: hashedPassword,
        role: 'OWNER',
        isActive: true,
      },
    });
    logger.info('✅ Usuário proprietário criado (owner@angola-localization.com / admin123)');

    logger.info('🎉 Seed concluído com sucesso!');
  } catch (error) {
    logger.error('❌ Erro durante o seed:', error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

// Run seed if this file is executed directly
if (require.main === module) {
  main()
    .catch((error) => {
      console.error(error);
      process.exit(1);
    });
}

export { main as seed };
